services:
  db:
    container_name: paybank-db
    image: postgres:13
    environment:
      - POSTGRES_USER=dba
      - POSTGRES_PASSWORD=dba
      - POSTGRES_DB=UserDB
      - POSTGRES_ROOT_PASSWORD=dba
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    restart: no
    networks:
      - skynet

  pgadmin:
    container_name: paybank-dbadm
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dba@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=dba
      - TZ=America/Sao_Paulo
    ports:
      - "15432:80"
    depends_on:
      - db
    restart: no
    networks:
      - skynet

  redis:
    container_name: paybank-redis
    image: redis:6.2
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "6379:6379"
    restart: no
    networks:
      - skynet

  redis-insight:
    container_name: paybank-redisadm
    image: redislabs/redisinsight:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: no
    networks:
      - skynet

  paybank-ms-auth:
    platform: linux/amd64
    container_name: paybank-ms-auth
    image: papitodev/paybank-ms-auth
    networks:
      - skynet
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://dba:dba@paybank-db:5432/UserDB
      - REDIS_HOST=paybank-redis
      - REDIS_PORT=6379
      - TZ=America/Sao_Paulo
    ports:
      - "3333:3333"
    restart: no

  paybank-ms-email:
    platform: linux/amd64
    container_name: paybank-ms-email
    image: papitodev/paybank-ms-email
    networks:
      - skynet
    depends_on:
      - paybank-ms-auth
    environment:
      - REDIS_HOST=paybank-redis
      - REDIS_PORT=6379
      - MAILTRAP_ACCOUNT_ID=3463410
      - MAILTRAP_TOKEN=b693ea1cac70f9af36414f548899f635
      - MAILTRAP_INBOX_ID=3463410
      - TZ=America/Sao_Paulo
    restart: no

  paybank-mf-auth:
    platform: linux/amd64
    container_name: paybank-mf-auth
    image: papitodev/paybank-mf-auth
    networks:
      - skynet
    depends_on:
      - paybank-ms-auth
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"
    restart: no

# Serviço de Jenkins para integração contínua
  jenkins:
    build: ./jenkins                # Usa o Dockerfile padrão localizado na pasta ./jenkins
    container_name: jenkins-server  # Define um nome amigável para o contêiner
    privileged: true                # Concede permissões elevadas ao contêiner (necessário para Docker-in-Docker)
    user: root                      # Executa o contêiner como usuário root para garantir permissões
    networks:
      - skynet                      # Conecta o Jenkins à rede Docker chamada 'skynet'
    restart: always                 # Reinicia automaticamente o contêiner em caso de falha
    environment:
      - TZ=America/Sao_Paulo        # Define o fuso horário do contêiner para São Paulo
    ports:
      - "8080:8080"                 # Mapeia a porta 8080 do host para a interface web do Jenkins
      - "50000:50000"               # Mapeia a porta para comunicação com agentes Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home             # Persiste dados do Jenkins no volume 'jenkins_home'
      - /var/run/docker.sock:/var/run/docker.sock  # Permite que o Jenkins use Docker do host

# Volumes
volumes:
  jenkins_home:                 # Persistência de dados do Jenkins    

networks:
  skynet:
    driver: bridge